spring.application.name=order-service

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/order_service
spring.datasource.username=root
spring.datasource.password=mysql

# Disable schema auto-creation because Flyway manages the schema.
spring.jpa.hibernate.ddl-auto=none

# Keep a dedicated port because product-service uses port 8080.
server.port=8081
inventory.url=http://localhost:8082
